Dev/motor drivers
cychitivav/pai pull request #26
Opened 2023-06-05 23:22 UTC by jsduenass

create a ROS node that handles the dual max 14870  motor driver
- include a custom version of the dual max 14870   library by pololu
- creates launch file intended to be used to run the robot 
- set up ROS parameters to use multiple instances of the same node. Setting the GPIO pins connected to the raspberry.

2023-06-05 23:23 UTC, jsduenass commented
@cychitivav @Canborda 
ready for review!!!

2023-06-06 03:24 UTC, cychitivav requested changes

2023-06-06 03:24 UTC, cychitivav commented on Dockerfile
> +
I do not see necessary this space
```suggestion
```

2023-06-06 03:24 UTC, cychitivav commented on LICENSE
I prefer to use this library like a submodule or create a new

2023-06-06 03:24 UTC, cychitivav commented on README.md
We are not using submodules yet

2023-06-06 03:24 UTC, cychitivav commented on config/drivers_pinout.yaml
why use one file with the parameters for the two drivers and then two other files, one for each driver?

2023-06-06 03:24 UTC, cychitivav commented on docs/source/imgs/raspberry-pi-3-PWM-pins.png
I prefer to do not upload images.

2023-06-06 03:24 UTC, cychitivav commented on lib/max14870-driver/LICENSE.txt
License file duplicated

2023-06-06 03:24 UTC, cychitivav commented on docs/source/index.md
> +![rpi pin out](./imgs/raspberry-pi-3-PWM-pins.png)
I would like to use this image
![image](https://github.com/cychitivav/pai/assets/30636259/018453a2-3278-494c-a706-0de937c5933a)
```suggestion
![rpi pin out](https://github.com/cychitivav/pai/assets/30636259/018453a2-3278-494c-a706-0de937c5933a)
```

2023-06-06 03:24 UTC, cychitivav commented on launch/run_robot.launch
> +     <rosparam file="$(find pai)/config/drivers.yaml" command="load" />
This cannot be loaded, and I think it is not necessary.
```suggestion
```

2023-06-06 03:24 UTC, cychitivav commented on launch/run_robot.launch
> +    </node>
Arguments cannot be loaded with `command="load"`

```suggestion
    <rosparam file="$(find pai)/config/driver_R_pinout.yaml" command="load" />
    <node   name="right_driver" 
            pkg="pai" output="screen"
            type="motor_driver.py" 
        >
        <param name="driver_pinout"              value="$(arg driver_R)"/>     
        <remap from="/wheel_A_ctrl/command" to="/front_right_wheel_ctrl/command"/>
        <remap from="/wheel_B_ctrl/command" to="/back_right_wheel_ctrl/command"/>
    </node>

    
    <!-- Left differential driver  -->
    <rosparam file="$(find pai)/config/driver_L_pinout.yaml" command="load" />
    <node   name="left_driver" 
            pkg="pai" output="screen"
            type="motor_driver.py"     
     >
        <param name="driver_pinout"              value="$(arg driver_L)"/>         
        <remap from="/wheel_A_ctrl/command" to="/front_left_wheel_ctrl/command"/>
        <remap from="/wheel_B_ctrl/command" to="/back_left_wheel_ctrl/command"/>    
    </node>
```

2023-06-06 03:24 UTC, cychitivav commented on scripts/motor_driver.py
> +        pin ={ 'FAULT':23, 'PWM2':24, 'PWM1':12, 'DIR2':16, 'DIR1':20, 'EN': 21}
This is a bit exaggerated, better to pass the default parameters and get the parameters using as namespace the node's name.
```suggestion
pin = rospy.get_param(rospy.get_name(), {'FAULT':23, 'PWM2':24, 'PWM1':12, 'DIR2':16, 'DIR1':20, 'EN': 21})
```

2023-06-06 03:24 UTC, cychitivav commented on scripts/motor_driver.py
> +    rospy.init_node("Computer", anonymous=True)
A little suggestion
```suggestion
    rospy.init_node("Driver", anonymous=True)
```

2023-06-06 03:24 UTC, cychitivav commented on scripts/motor_driver.py
As I said before, I prefer not to use the dual_max14870_rpi library.

2023-06-06 12:47 UTC, jsduenass commented on LICENSE
Alright I will fork the library repo and then added here as a submodule

2023-06-06 12:51 UTC, jsduenass commented on lib/max14870-driver/LICENSE.txt
This would still hold if we use the submodule

2023-06-06 13:19 UTC, jsduenass commented on config/drivers_pinout.yaml
I was still testing and didn't know which approach was better to use a config file for both motor or separate each in its config file. I decided the latter so I remove this file

2023-06-06 13:20 UTC, jsduenass commented
alright @cychitivav  how do you find the changes?

2023-06-06 14:21 UTC, cychitivav commented on lib/max14870-driver/LICENSE.txt
and why not create our own code?.

2023-06-06 14:22 UTC, cychitivav commented
In general lgtm, but I prefer to create our own code, I see that the `Driver` class inherits from `DualMotorDriver` and I think they are the same thing. This would go against the OOP paradigm.

2023-06-06 14:31 UTC, jsduenass commented
It is true that the Driver class is not doing that much is just working as a wrapper to communicate with the ROS messages. And the library used is not that complex. However, I think that the implementation of this change would better be handle in a separate issue and merge what we have so far.

2023-06-06 14:32 UTC, cychitivav requested changes

2023-06-06 14:32 UTC, cychitivav commented on launch/run_robot.launch
> +        <param name="driver_pinout"              value="$(arg driver_L)"/>
It is also necessary to remove the `args`.
```suggestion
    <rosparam file="$(find pai)/config/driver_R_pinout.yaml" command="load" />
    <node   name="right_driver" 
            pkg="pai" output="screen"
            type="motor_driver.py" 
        >
        <remap from="/wheel_A_ctrl/command" to="/front_right_wheel_ctrl/command"/>
        <remap from="/wheel_B_ctrl/command" to="/back_right_wheel_ctrl/command"/>
    </node>

    
    <!-- Left differential driver  -->
    <rosparam file="$(find pai)/config/driver_L_pinout.yaml" command="load" />
    <node   name="left_driver" 
            pkg="pai" output="screen"
            type="motor_driver.py"     
     >   
```

2023-06-06 14:34 UTC, cychitivav commented
> It is true that the Driver class is not doing that much is just working as a wrapper to communicate with the ROS messages. And the library used is not that complex. However, I think that the implementation of this change would better be handle in a separate issue and merge what we have so far.

Ok, I think you are right, for now let's fix the last changes and in another PR or issue we will discuss about the submodule.

2023-06-06 14:36 UTC, jsduenass commented
> Ok, I think you are right, for now let's fix the last changes and in another PR or issue we will discuss about the submodule

Sounds good

2023-06-06 14:40 UTC, jsduenass commented on launch/run_robot.launch
> +        <param name="driver_pinout"              value="$(arg driver_L)"/>
I think with this change both nodes will be left with the parameter of the last definition. in this case `driver_L_pinout.yaml`.
but let's include the change to see how it goes.

2023-06-06 14:43 UTC, cychitivav approved these changes

2023-06-06 14:45 UTC, merged